/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#261900',
        'tertiary-fixed-dim': '#c1c6d7',
        'secondary-fixed': '#ffdea5',
        'on-primary-container': '#76849f',
        'primary-fixed-dim': '#b9c7e4',
        'on-secondary-fixed-variant': '#5d4201',
        'tertiary-container': '#161c27',
        'primary-fixed': '#d6e3ff',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e1e3e4',
        'secondary-container': '#fed488',
        'secondary': '#775a19',
        'secondary-gold': '#c5a059',
        'secondary-gold-light': '#fdf6e7',
        'surface-bright': '#f8f9fa',
        'inverse-on-surface': '#f0f1f2',
        'on-background': '#191c1d',
        'tertiary-fixed': '#dde2f3',
        'surface': '#f8f9fa',
        'on-tertiary-fixed-variant': '#414754',
        'surface-container': '#edeeef',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#39475f',
        'on-error': '#ffffff',
        'error': '#ba1a1a',
        'surface-container-highest': '#e1e3e4',
        'secondary-fixed-dim': '#e9c176',
        'on-secondary': '#ffffff',
        'tertiary': '#000000',
        'on-surface-variant': '#44474d',
        'surface-container-low': '#f3f4f5',
        'inverse-surface': '#2e3132',
        'primary': '#0a192f',
        'primary-dark': '#07111e',
        'primary-light': '#122543',
        'on-tertiary-fixed': '#161c27',
        'on-secondary-container': '#785a1a',
        'outline': '#75777e',
        'primary-container': '#0d1c32',
        'on-tertiary-container': '#7e8493',
        'surface-dim': '#d9dadb',
        'surface-tint': '#515f78',
        'outline-variant': '#c5c6cd',
        'on-surface': '#191c1d',
        'inverse-primary': '#b9c7e4',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'surface-container-high': '#e7e8e9',
        'background': '#f8f9fa',
        'on-primary-fixed': '#0d1c32'
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px'
      },
      spacing: {
        'gutter': '24px',
        'margin-desktop': '64px',
        'unit': '8px',
        'margin-mobile': '20px',
        'container-max': '1280px'
      },
      fontFamily: {
        'display': ['"Hanken Grotesk"', 'sans-serif'],
        'display-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-md': ['"Hanken Grotesk"', 'sans-serif'],
        'body': ['"Inter"', 'sans-serif'],
        'body-lg': ['"Inter"', 'sans-serif'],
        'body-md': ['"Inter"', 'sans-serif'],
        'label-caps': ['"Inter"', 'sans-serif']
      }
    }
  },
  plugins: [],
};
